const TIMESTAMP_CACHE_PREFIX = "TCP_";
const SESSION_CACHE_PREFIX = "SCP_";
const VISITOR_TOKEN = "8a965ba5-2e11-483d-aa74-a9a27792f49e";

module.exports = {
	TIMESTAMP_CACHE_PREFIX,
	VISITOR_TOKEN,
	SESSION_CACHE_PREFIX,
};
