const TIMESTAMP_CACHE_PREFIX = "TCP_";
const EXCHANGE_RATE_CACHE_PREFIX = "EXR_";
const SESSION_CACHE_PREFIX = "SCP_";
const SUSPEND_CACHE_PREFIX = "SUSPEND_";


const VISITOR_TOKEN = "8a965ba5-2e11-483d-aa74-a9a27792f49e";

module.exports = {
	TIMESTAMP_CACHE_PREFIX,
	VISITOR_TOKEN,
	EXCHANGE_RATE_CACHE_PREFIX,
	SESSION_CACHE_PREFIX,
	SUSPEND_CACHE_PREFIX
};
