# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Heroku CI
on:
  push:
    branches:
      - main
    tags:
      - v1
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      username:
        description: 'User responsible to invoke Herkou CI Workflow'
        type: string
        required: false
        default: Pipeline
env:
  HEROKU_APP_NAME: ecommerce-service-ifa
  HEROKU_API_KEY: b9349584-46f9-44f1-a4c7-7d95454600e3
jobs:
  deploy-to-heroku:
    runs-on: ubuntu-latest
    steps:
      - name: "GIT INIT"
        run: git init
      - name: "Install Dependencies"
        run: yarn install
      - name: "Push to Heroku"
        run: git push https://heroku:b9349584-46f9-44f1-a4c7-7d95454600e3@git.heroku.com/ecommerce-service-ifa.git HEAD
